markdown: kramdown
exclude:
  - create-thumbnails.bat
  - README.md
  - vendor

title: 'Yet Another TEch bLog'
# encode: http://wbwip.com/wbw/emailencoder.html
email: '&#098;&#108;&#111;&#103;&#064;&#107;&#114;&#097;&#109;&#111;&#108;&#105;&#115;&#046;&#099;&#122;'

#excerpt_separator: <!--more-->
